/*
 * BlockConfiguratorFrame.java
 *
 * Created on 6. März 2008, 12:50
 */

package gralej.blocks.configurator;

import gralej.blocks.BlockLayout;
import gralej.blocks.BlockPanelStyle;
import gralej.blocks.LabelStyle;
import java.awt.BorderLayout;
import javax.swing.UIManager;

/**
 *
 * @author  Martin
 */
public class BlockConfiguratorFrame extends javax.swing.JFrame implements BlockConfigurator.Handler {
    
    BlockLayoutEditor _layed;
    LabelStyleEditor _labed;
    MiscSettingsEditor _misced;
    BlockConfigurator _configurator;
    
    public BlockConfiguratorFrame() {
        initComponents();
        
        _configurator = new BlockConfigurator(this);
        
        _treePanel.setLayout(new BorderLayout());
        _treePanel.add(_configurator.getUI());
        pack();
    }
    
    private MiscSettingsEditor misced() {
        if (_misced == null)
            _misced = new MiscSettingsEditor(this, false, _configurator.getStyle());
        return _misced;
    }
    
    private BlockLayoutEditor layed() {
        if (_layed == null)
            _layed = new BlockLayoutEditor(this, false, _configurator.getStyle());
        return _layed;
    }
    
    private LabelStyleEditor labed() {
        if (_labed == null)
            _labed = new LabelStyleEditor(this, false, _configurator.getStyle());
        return _labed;
    }
    
    public void modifyLabelStyle(LabelStyle style) {
        labed().reset(style);
        if (!labed().isVisible())
            labed().setVisible(true);
    }

    public void modifyBlockLayout(BlockLayout layout) {
        layed().reset(layout);
        if (!layed().isVisible())
            layed().setVisible(true);
    }
    
    public void modifyMiscSettings() {
        if (!misced().isVisible())
            misced().setVisible(true);
    }

    public void updateMessage(String message) {
        _lblMessage.setText(message);
    }

    public void clearMessage() {
        _lblMessage.setText("");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        _bCommit = new javax.swing.JButton();
        _bReset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        _lblMessage = new javax.swing.JLabel();
        _treePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AVM Tree View Configurator");

        _bCommit.setText("Commit");
        _bCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _bCommitActionPerformed(evt);
            }
        });

        _bReset.setText("Reset");
        _bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _bResetActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        _lblMessage.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_bCommit, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(_bReset, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {_bCommit, _bReset});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(_bReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_bCommit))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout _treePanelLayout = new javax.swing.GroupLayout(_treePanel);
        _treePanel.setLayout(_treePanelLayout);
        _treePanelLayout.setHorizontalGroup(
            _treePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );
        _treePanelLayout.setVerticalGroup(
            _treePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(_treePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_treePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _bCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__bCommitActionPerformed
        _configurator.getStyle().updatePreferences();
    }//GEN-LAST:event__bCommitActionPerformed

    private void _bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__bResetActionPerformed
        BlockPanelStyle s = new BlockPanelStyle();
        _configurator.setStyle(s);
        
        layed().setBlockPanelStyle(s);
        layed().setVisible(false);
        
        labed().setBlockPanelStyle(s);
        labed().setVisible(false);
        
        misced().reset(s);
        misced().setVisible(false);
    }//GEN-LAST:event__bResetActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (Exception e) {
                    System.err.println("-- failed to set the system's native look and feel");
                }
                BlockConfiguratorFrame dialog = new BlockConfiguratorFrame();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _bCommit;
    private javax.swing.JButton _bReset;
    private javax.swing.JLabel _lblMessage;
    private javax.swing.JPanel _treePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
