/*
 * FinderDialog.java
 *
 * Created on 8. März 2008, 02:44
 */

package gralej.blocks.finder;

import gralej.blocks.BlockPanel;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author  Martin
 */
public class FinderDialog extends javax.swing.JDialog {
    
    FinderOptions opts;
    
    /** Creates new form FinderDialog */
    FinderDialog(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        JComponent c = (JComponent) getContentPane();
        c.getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT).put(
                KeyStroke.getKeyStroke("ENTER"), "find");
        c.getActionMap().put("find",
            new AbstractAction() {
                public void actionPerformed(ActionEvent e) {
                    _bFindActionPerformed(e);
                }
        });
        c.getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT).put(
                KeyStroke.getKeyStroke("ESCAPE"), "close");
        c.getActionMap().put("close",
            new AbstractAction() {
                public void actionPerformed(ActionEvent e) {
                    _bCloseActionPerformed(e);
                }
        });
    }
    
    public static Finder getFinder(Frame parent, BlockPanel panel) {
        FinderDialog dlg = new FinderDialog(parent, true);
        dlg.setVisible(true);
        if (dlg.opts != null)
            return Finder.newInstance(dlg.opts, panel);
        return null;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        _txt = new javax.swing.JTextField();
        _bFind = new javax.swing.JButton();
        _bClose = new javax.swing.JButton();
        _chkRegex = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Find");

        jLabel1.setText("Search for:");

        _bFind.setText("Find");
        _bFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _bFindActionPerformed(evt);
            }
        });

        _bClose.setText("Close");
        _bClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _bCloseActionPerformed(evt);
            }
        });

        _chkRegex.setMnemonic('r');
        _chkRegex.setText("Regular Expression");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(_chkRegex)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_bClose))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(_bFind)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {_bClose, _bFind});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_bFind))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_bClose)
                    .addComponent(_chkRegex))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _bCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__bCloseActionPerformed
        dispose();
}//GEN-LAST:event__bCloseActionPerformed

    private void _bFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__bFindActionPerformed
        opts = new FinderOptions();
        opts.text = _txt.getText();
        opts.regex = _chkRegex.isSelected();
        dispose();
    }//GEN-LAST:event__bFindActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FinderDialog dialog = new FinderDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _bClose;
    private javax.swing.JButton _bFind;
    private javax.swing.JCheckBox _chkRegex;
    private javax.swing.JTextField _txt;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
