/*
 *  $Id$
 *
 *  This file is part of the Gralej system
 *     http://code.google.com/p/gralej/
 *
 *  Gralej is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Gralej is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package gralej.parsers;

/**
 * An exception thrown by {@link GraleParserFactory} in case the protocol type
 * cannot be handled.
 * 
 * @author no
 * 
 */
public class UnsupportedProtocolException extends Exception {

    /**
     * (generated by Eclipse)
     */
    private static final long serialVersionUID = -7733686791936268372L;

    public UnsupportedProtocolException() {
        super();
    }

    public UnsupportedProtocolException(String message, Throwable cause) {
        super(message, cause);
    }

    public UnsupportedProtocolException(String message) {
        super(message);
    }

    public UnsupportedProtocolException(Throwable cause) {
        super(cause);
    }

}
