package gralej.parsers;

/**
 * An exception thrown by {@link GraleParserFactory} in case the protocol type
 * cannot be handled.
 * 
 * @author no
 * 
 */
public class UnsupportedProtocolException extends Exception {

    /**
     * (generated by Eclipse)
     */
    private static final long serialVersionUID = -7733686791936268372L;

    public UnsupportedProtocolException() {
        super();
    }

    public UnsupportedProtocolException(String message, Throwable cause) {
        super(message, cause);
    }

    public UnsupportedProtocolException(String message) {
        super(message);
    }

    public UnsupportedProtocolException(Throwable cause) {
        super(cause);
    }

}
